


services:
  nginx:
    container_name: domain-name-nginx
    hostname: domain-name-nginx
    build: ./volumes/build/nginx
    volumes:
      - ./volumes/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro #Конфигурация nginx.
      - ./volumes/etc/nginx/sites-enabled:/etc/nginx/sites-enabled:ro #Конфигурация площадок.
      - ./volumes/etc/nginx/ssl:/etc/nginx/ssl:ro #сертификаты
      - ./log/nginx:/var/log/nginx
      - ./backend:/var/www/domain-name #Домашняя директория
      - ./frontend:/var/www/frontend
    ports:
      - "80:80"
    links:
      - php-fpm
      - frontend
    restart:
      always
    networks:
      default:
        ipv4_address: 172.16.1.8

  frontend:
    container_name: domain-name-frontend
    hostname: domain-name-frontend
    build: ./volumes/build/frontend
    command: bash -c "npm i && nohup npm run dev"
    ports:
      - "3333:3333"
      - "3332:3332"
    volumes:
      - ./frontend:/var/www/frontend
      - ./frontend/node_modules:/var/www/frontend/node_modules
    networks:
      default:
        ipv4_address: 172.16.1.4

  php-fpm:
    container_name: domain-name-php-fpm
    hostname: domain-name-php-fpm
    build: ./volumes/build/php-fpm8.3
    ports:
      - "9000:9010"
      - "22:22"
    volumes:
      - ./volumes/etc/php/fpm.pool.d/domain.conf:/usr/local/etc/php-fpm.d/domain.conf:ro #Конфигурация площадки
      - ./volumes/etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro #Конфигурация php для php-fpm
      - ./log/php:/var/log/php #log файлы
      - ./backend:/var/www/domain-name #Домашняя директория
      - ./volumes/build/.ssh/authorized_keys:/root/.ssh/authorized_keys
    cap_add:
      - SYS_NICE
      - DAC_READ_SEARCH
    restart: always
    networks:
      default:
        ipv4_address: 172.16.1.5

  mysql:
    container_name: domain-name-mysql
    hostname: domain-name-mysql
    build: ./volumes/build/mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/lib:/var/lib/mysql #Директория БД.
      - ./mysql/log:/var/log/mysql #log файл
      - ./volumes/mysql/conf.d:/etc/mysql/conf.d:ro #Конфигурация mysql.
    networks:
      default:
        ipv4_address: 172.16.1.6

  phpmyadmin:
    container_name: domain-name-phpadmin
    hostname: domain-name-phpadmin
    build: ./volumes/build/phpmyadmin
    links:
      - mysql
    environment:
      - PMA_HOST=mysql
      - DATABASE_PORT_NUMBER=3306
      - PHPMYADMIN_ALLOW_REMOTE_CONNECTIONS=true
      - DATABASE_ENABLE_SSL=false
    ports:
      - "8001:80"
    networks:
      default:
        ipv4_address: 172.16.1.7

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24

volumes:
  node_modules: